image:
  file: .gitpod.dockerfile

tasks:
  - name: Dev Server
    init: yarn
    command: yarn dev

ports:
  - port: 3000 # Web app
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - mikestead.dotenv
    - graphql.vscode-graphql
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - pflannery.vscode-versionlens
    - wix.vscode-import-cost
    - formulahendry.auto-close-tag
    - github.github-vscode-theme
    - gitlab.gitlab-workflow
    - bradlc.vscode-tailwindcss
    - bierner.markdown-preview-github-styles
    - editorconfig.editorconfig
    - pkief.material-icon-theme
