import React, { useState } from "react";

import Head from "next/head";

import dayjs from "dayjs";
import sum from "lodash.sum";

const parameters: Array<dayjs.UnitType> = [
  "year",
  "month",
  "day",
  "hour",
  "minute",
  "second",
];

const reduceOverview = (
  dateFrom: dayjs.Dayjs,
  dateTo: dayjs.Dayjs,
  diffs: Array<number>
) => {
  const newDiffs: Array<number> = [];

  let index = 0;
  for (const diff of diffs) {
    if (index === 0) {
      newDiffs.push(diff);
    } else {
      const reducedDate = dateTo.subtract(
        diffs[index === 0 ? index : index - 1],
        parameters[index === 0 ? index : index - 1]
      );
      const newDiff = reducedDate.diff(dateFrom, parameters[index]);
      newDiffs.push(newDiff);
    }

    index++;
  }

  return newDiffs;
};

const formatDiffs = (diffs: Array<number>): string => {
  const outputValues = [];
  const wentThrough = [];

  let index = 0;
  for (const unit of diffs) {
    wentThrough.push(unit);
    if ((unit !== 0 && wentThrough !== []) || sum(wentThrough) !== 0) {
      outputValues.push(`${unit} ${parameters[index]}${unit === 1 ? "" : "s"}`);
    }
    index++;
  }

  return outputValues.join(" ");
};

const getDiffParams = (from: dayjs.Dayjs, to: dayjs.Dayjs): Array<number> => {
  const diffs: Array<number> = [];

  for (const param of parameters) {
    const difference = to.diff(from, param);
    diffs.push(difference);
  }

  return diffs;
};

export default function Home() {
  const [date, setDate] = useState<Date>(new Date("Dec 24 2023"));
  const parsed = dayjs(date);
  const [today, setToday] = useState(dayjs());

  setInterval(() => {
    setToday(dayjs());
  }, 1000);

  const diffs = getDiffParams(today, parsed);
  const diffParams = formatDiffs(reduceOverview(today, parsed, diffs));

  return (
    <div className="flex flex-col items-center justify-between h-screen">
      <Head>
        <title>CountDowner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav className="w-screen text-xm gap-10 bg-[#262A2B] py-4 cursor-pointer">
          <span>Create countdown</span>
          <a
            href="https://github.com/filiptronicek/CountDowner"
            target="_blank"
            rel="noreferrer noopener"
          >
            Source code
          </a>
        </nav>
      </header>

      <main className="text-center">
        <div>
          <div className="text-7xl">Christmas 2021</div>
          <div className="text-3xl">
            Counting down to {parsed.format("D/M/YYYY")}
          </div>
          <div id="countdown-area" className="mt-5 text-4xl">
            {diffParams}
          </div>
        </div>
      </main>

      <footer>By @filiptronicek with 💖</footer>
    </div>
  );
}
